<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Prefer32Bit>False</Prefer32Bit>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Prefer32Bit>False</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataAccess\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="DataAccess\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="DataAccess\**" />
    <None Remove="Services\**" />
    <Page Remove="DataAccess\**" />
    <Page Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\DM.png" />
    <None Remove="Images\GV.png" />
    <None Remove="Images\HAT.png" />
    <None Remove="Images\JK_G.png" />
    <None Remove="Images\Nidec-Logo.jpg" />
    <None Remove="Images\Nidec_Logo-removebg.png" />
    <None Remove="Images\Nidec_Logo.png" />
    <None Remove="Images\Nidec_Logo_RemoveBG.png" />
    <None Remove="Images\SS_ESD_G.png" />
    <None Remove="Images\SS_ESD_W.png" />
    <None Remove="Images\S_ESD.png" />
    <None Remove="Images\S_NonESD.png" />
    <None Remove="Images\TR_G.png" />
    <None Remove="Images\TR_M_DG.png" />
    <None Remove="Images\TR_W.png" />
    <None Remove="Images\TS_ESD_G.png" />
    <None Remove="Images\TS_ESD_W.png" />
    <None Remove="Images\TS_G.png" />
    <None Remove="Images\TS_W.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\DM.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\JK_G.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\SS_ESD_G.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\SS_ESD_W.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\S_ESD.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\S_NonESD.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TR_M_DG.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TS_ESD_G.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TS_W.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TS_ESD_W.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HAT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Nidec_Logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="EPPlus" Version="7.6.1" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.1.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.PhosphorIcons" Version="5.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Interop.CoreScanner">
      <HintPath>..\..\B600044177\NidecIDM\NidecIDM\obj\Debug\Interop.CoreScanner.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Nidec-Logo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Nidec_Logo_RemoveBG.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TR_W.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TS_G.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TR_G.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
