// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NidecUniform.Models;

#nullable disable

namespace NidecUniform.Migrations
{
    [DbContext(typeof(NidecUniformContext))]
    [Migration("20250307014908_CreateRawDataTable")]
    partial class CreateRawDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NidecUniform.Models.DeliveryDetail", b =>
                {
                    b.Property<int>("DeliveryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeliveryDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryDetailId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("QuantityDelivered")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeliveryDetailId")
                        .HasName("PK__Delivery__EFD2C287B58D7321");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("ProductId");

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("NidecUniform.Models.MDelivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeliveryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeliveredBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeliveryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmpolyeeId")
                        .HasColumnType("int")
                        .HasColumnName("Empolyee_ID");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DeliveryId")
                        .HasName("PK__Deliveri__626D8FEED074CDB0");

                    b.HasIndex("EmpolyeeId");

                    b.HasIndex("RequestId");

                    b.ToTable("M_Deliveries", (string)null);
                });

            modelBuilder.Entity("NidecUniform.Models.MEmployee", b =>
                {
                    b.Property<int>("EmpolyeeId")
                        .HasColumnType("int")
                        .HasColumnName("Empolyee_ID");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmpolyeeId")
                        .HasName("PK_M_Empolyee");

                    b.ToTable("M_Employees", (string)null);
                });

            modelBuilder.Entity("NidecUniform.Models.MProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("M_Products", (string)null);
                });

            modelBuilder.Entity("NidecUniform.Models.MRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmpolyeeId")
                        .HasColumnType("int")
                        .HasColumnName("Empolyee_ID");

                    b.Property<DateTime?>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RequestId")
                        .HasName("PK__M_Reques__33A8519A60486747");

                    b.HasIndex("EmpolyeeId");

                    b.ToTable("M_Requests", (string)null);
                });

            modelBuilder.Entity("NidecUniform.Models.RequestDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("QuantityApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("QuantityDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DetailId")
                        .HasName("PK__RequestD__135C314DC9F0A3FF");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDetails");
                });

            modelBuilder.Entity("NidecUniform.Models.DeliveryDetail", b =>
                {
                    b.HasOne("NidecUniform.Models.MDelivery", "Delivery")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("DeliveryId")
                        .IsRequired()
                        .HasConstraintName("FK_DeliveryDetails_Delivery");

                    b.HasOne("NidecUniform.Models.MProduct", "Product")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_DeliveryDetails_Product");

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NidecUniform.Models.MDelivery", b =>
                {
                    b.HasOne("NidecUniform.Models.MEmployee", "Empolyee")
                        .WithMany("MDeliveries")
                        .HasForeignKey("EmpolyeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Deliveries_Employee");

                    b.HasOne("NidecUniform.Models.MRequest", "Request")
                        .WithMany("MDeliveries")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Deliveries_Request");

                    b.Navigation("Empolyee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("NidecUniform.Models.MRequest", b =>
                {
                    b.HasOne("NidecUniform.Models.MEmployee", "Empolyee")
                        .WithMany("MRequests")
                        .HasForeignKey("EmpolyeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_Employee");

                    b.Navigation("Empolyee");
                });

            modelBuilder.Entity("NidecUniform.Models.RequestDetail", b =>
                {
                    b.HasOne("NidecUniform.Models.MProduct", "Product")
                        .WithMany("RequestDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestDetails_Product");

                    b.HasOne("NidecUniform.Models.MRequest", "Request")
                        .WithMany("RequestDetails")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestDetails_Request");

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("NidecUniform.Models.MDelivery", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("NidecUniform.Models.MEmployee", b =>
                {
                    b.Navigation("MDeliveries");

                    b.Navigation("MRequests");
                });

            modelBuilder.Entity("NidecUniform.Models.MProduct", b =>
                {
                    b.Navigation("DeliveryDetails");

                    b.Navigation("RequestDetails");
                });

            modelBuilder.Entity("NidecUniform.Models.MRequest", b =>
                {
                    b.Navigation("MDeliveries");

                    b.Navigation("RequestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
